on:
  push:
    tags:
    - '*'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luckyhasuradocker/lucky-crystal
          tags: cache, ${{ env.VERSION }}
          cache_froms: luckyhasuradocker/lucky-crystal:cache